name: scattergories
version: 0.0.1
verbatim:
  cabal-version: '>= 1.10'
author:
  - Brandon Chinn <brandonchinn178@gmail.com>
maintainer:
  - Brandon Chinn <brandonchinn178@gmail.com>

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

dependencies:
  - aeson
  - base
  - containers
  - file-embed
  - MonadRandom
  - random-shuffle
  - text

library:
  source-dirs: src

executable:
  source-dirs: exe
  main: Main.hs
  dependencies:
    - scattergories
    - servant-server
    - servant-websockets
    - websockets
    - warp
